baseURL: http://localhost:1313/blog/
languageCode: FR-fr
title: Chez Callan
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
  env: development # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Allan Cerveaux - https://github.com/"
  author: Allan Cerveaux
  defaultTheme: auto
  ShowShareButtons: false
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  profileMode:
    enabled: true
    title: "Hello I'm Allan Cerveaux 👋" # optional default will be site title
    subtitle: "Développeur Web / Web Mobile"
  socialIcons:
    - name: Github
      url: "https://github.com/AllanCerveaux"
    - name: Twitter
      url: "https://twitter.com/CerveauxAllan"
    - name: Linkedin
      url: "https://www.linkedin.com/in/allancerveaux/"
    - name: RsS
      url: "index.xml"
  editPost:
      URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
      Text: "Suggest Changes" # edit text
      appendFilePath: true
  reveal_hugo:
    highlight_theme: "github"
# menu:
#   main:
#     - identifier: articles
#       name: Articles
#       url: /posts/
#       weight: 0
# Hugo Config
outputFormats:
  Reveal:
    baseName: index
    mediaType: text/html
    isHTML: true

markup:
  highlight:
    codeFences: false
